openapi: 3.0.3
info:
  title: Reactive Editor
  description: Reactive Editor
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /auth:
    post:
      summary: 'Create session from Username & Password'
      security: [ ]
      responses:
        200:
          description: 'Logged in successfully'
    delete:
      summary: 'Logout of session'
      responses:
        204:
          description: 'Removed/logged out of session'
    put:
      summary: 'Attempt to refresh current session'
      responses:
        '200':
            description: 'Successfully refresh token'

components:
  securitySchemes:
    BearerJWT:
      type: 'http'
      scheme: 'bearer'
      bearerFormat: 'jwt'

security:
  - BearerJWT: [ ]